version: '3.3'

services:
  frontend:
    depends_on:
      - backend
    build: ../rq-react-movies
    ports:
      - 80:3000

  backend:
    depends_on:
      - db
    build: ./
    ports:
      - 3333:3333
    environment:
      rqMoviesDb: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - rqmovies:/data/db

volumes:
  rqmovies:
